/*
 * Copyright (c) 2025, Corta Labs
 * BSD 2-Clause License. See LICENSE.
 */
package com.cortalabs.osrs.analytics.collector;

import com.cortalabs.osrs.analytics.dto.PluginPayload;
import java.io.IOException;
import java.io.InputStream;
import java.time.Instant;
import java.util.Properties;
import net.runelite.api.Client;
import net.runelite.api.Player;

/**
 * Shared helpers for populating the common {@link PluginPayload} fields from
 * live client state. Kept in one place so every collector stamps rsn / world /
 * timestamp / version identically.
 */
public final class Payloads
{
	/** Plugin version; must satisfy the backend's {@code \d+\.\d+\.\d+} contract. */
	public static final String PLUGIN_VERSION = readPluginVersion();

	/**
	 * Classpath resource carrying the plugin version, generated by build.gradle's
	 * {@code createProperties} task as {@code pluginVersion=$project.version} and
	 * bundled into the jar. build.gradle is the single source of version truth.
	 */
	private static final String VERSION_RESOURCE = "/version.ini";
	/** Key inside {@code VERSION_RESOURCE}. */
	private static final String VERSION_KEY = "pluginVersion";
	/**
	 * Emitted only when the generated version resource is absent or malformed — a
	 * packaging defect, never a real release. Kept as a valid dotted-triple so a
	 * broken build degrades visibly instead of having every payload rejected by the
	 * backend's version CHECK; it is a failure sentinel, not a second copy of the
	 * real version.
	 */
	static final String VERSION_UNAVAILABLE = "0.0.0";

	/** RuneLite pads display names with a non-breaking space; normalize it out. */
	private static final char NBSP = ' ';

	private Payloads()
	{
	}

	/**
	 * Read the plugin version from the build-generated {@code /version.ini} classpath
	 * resource, whose sole author is build.gradle's {@code createProperties} task
	 * ({@code pluginVersion=$project.version}). This reads the build's projection
	 * rather than restating it, so there is one source of version truth and no third
	 * copy to drift. Returns {@link #VERSION_UNAVAILABLE} only if the generated
	 * resource is missing or malformed (a build/packaging defect). Package-private so
	 * the derivation is directly testable.
	 */
	static String readPluginVersion()
	{
		try (InputStream in = Payloads.class.getResourceAsStream(VERSION_RESOURCE))
		{
			if (in == null)
			{
				return VERSION_UNAVAILABLE;
			}
			Properties props = new Properties();
			props.load(in);
			String version = props.getProperty(VERSION_KEY);
			if (version == null || version.trim().isEmpty())
			{
				return VERSION_UNAVAILABLE;
			}
			return version.trim();
		}
		catch (IOException ex)
		{
			return VERSION_UNAVAILABLE;
		}
	}

	public static String isoNow()
	{
		return Instant.now().toString();
	}

	/**
	 * Return the local player's display name, sanitized to the backend's 1-12
	 * char contract, or {@code null} when unavailable.
	 */
	public static String rsn(Client client)
	{
		Player player = client.getLocalPlayer();
		if (player == null)
		{
			return null;
		}
		String name = player.getName();
		if (name == null)
		{
			return null;
		}
		name = name.replace(NBSP, ' ').trim();
		if (name.isEmpty() || name.length() > 12)
		{
			return null;
		}
		return name;
	}

	/**
	 * Stamp the common payload fields. {@code world} is included only when it is
	 * within the backend's accepted 300-600 range (otherwise left null, which is
	 * valid for every payload except session events).
	 */
	public static void base(PluginPayload payload, Client client, String rsn)
	{
		payload.rsn = rsn;
		int world = client.getWorld();
		payload.world = (world >= 300 && world <= 600) ? Integer.valueOf(world) : null;
		payload.timestamp = isoNow();
		payload.pluginVersion = PLUGIN_VERSION;
	}
}
